language: python
python:
  - "2.7.15"
cache: pip
services:
  - mongodb
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -v -s tests -p "*tests.py"
